[package]

name = "sprs"
description = "A sparse matrix library"
version = "0.6.4"
authors = ["Vincent Barrielle <vincent.barrielle@m4x.org>"]

readme = "README.rst"
license = "MIT OR Apache-2.0"
repository = "https://github.com/vbarrielle/sprs"
documentation = "https://docs.rs/sprs"
keywords = ["sparse", "matrix", "linear", "algebra"]

exclude = [
    "data/*"
]

[features]
default = ["alga"]

[dependencies]
num-traits = "0.1.32"
ndarray = ">=0.11, <0.13"
alga = { version = "0.5", optional = true }
num-complex = "0.1.36"
serde = "1.0"
serde_derive = "1.0"

[dev-dependencies]
bencher = "0.1"
tempdir = "0.3.5"
bincode = "1.0.1"

[[bench]]
name = "suite"
harness = false

[[bench]]
name = "sparse_dense_products"
harness = false

[workspace]
members = [
    "sprs-ldl",
    "suitesparse_bindings/suitesparse_ldl_sys",
    "suitesparse_bindings/sprs_suitesparse_ldl",
]
