[package]

name = "sprs"
description = "A sparse matrix library"
version = "0.6.0"
authors = ["Vincent Barrielle <vincent.barrielle@m4x.org>"]

readme = "README.rst"
license = "MIT OR Apache-2.0"
repository = "https://github.com/vbarrielle/sprs"
documentation = "https://vbarrielle.github.io/sprs/doc/sprs/"
keywords = ["sparse", "matrix", "linear", "algebra"]

exclude = [
    "data/*"
]

[features]
default = ["alga"]

[dependencies]
num-traits = "0.1.32"
ndarray = "0.10.0"
alga = { version = "0.5", optional = true }
num-complex = "0.1.36"
itertools = "0.6.0"

[dev-dependencies]
bencher = "0.1"
tempdir = "0.3.5"

[[bench]]
name = "suite"
harness = false
